### ISSUE TITLE
Invisible/transparent tires

### ISSUE THREAD

**Issue by dawwin** [virtual-programming/dirtshowdown-linux#13] opened 2015-10-11 12:00 UTC
All tires are transparent when I'm in game or watching replays.
On loading screens etc. everything looks fine.

**In-game:**
![image](https://cloud.githubusercontent.com/assets/6729869/10416315/c5475c00-7012-11e5-86b3-31314793fe4b.png)
![image](https://cloud.githubusercontent.com/assets/6729869/10416650/ce5d06da-701e-11e5-932a-3d58a2069d25.png)

**Loading screen:**
![image](https://cloud.githubusercontent.com/assets/6729869/10416343/cea4a4f0-7013-11e5-9133-9e91d5c2a838.png)

eon.txt: https://gist.github.com/dawwin/6973c05d859cca79e9ff
Steam system information: https://gist.github.com/dawwin/041406d3d1c054852d06

My video card: GeForce GT 630M with 1GB RAM (it's a mobile card using optimus technology)
Nvidia driver version: 355.11 (running with bumblebee and primus)
OS: Ubuntu 14.04.3 x64

**Comment by vpltd-peterm** [comment] 2015-10-11 18:56
Duplicate of #4

**Closed by vpltd-peterm** 2015-10-11 18:56 UTC
